# - id: doi:10.1371/journal.pcbi.1007128
#   type: paper
#   description: Lorem ipsum _dolor_ **sit amet**, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
#   date: 2020-12-4
#   image: https://journals.plos.org/ploscompbiol/article/figure/image?size=inline&id=info:doi/10.1371/journal.pcbi.1007128.g001&rev=2
#   buttons:
#     - type: manubot
#       link: https://greenelab.github.io/meta-review/
#     - type: source
#       text: Manuscript Source
#       link: https://github.com/greenelab/meta-review
#     - type: website
#       link: http://manubot.org/
#   tags:
#     - open science
#     - collaboration
#   repo: greenelab/meta-review

# - id: doi:10.1016/j.csbj.2020.05.017
#   image: https://ars.els-cdn.com/content/image/1-s2.0-S2001037020302804-gr1.jpg

# - id: doi:10.7554/eLife.32822
#   image: https://iiif.elifesciences.org/lax:32822%2Felife-32822-fig8-v3.tif/full/863,/0/default.webp

- id: arxiv:2006.08848
  type: paper
  description: A novel personalized federated learning algorithm using Moreau envelopes that addresses statistical heterogeneity in federated learning by enabling each client to learn a personalized model while benefiting from the global knowledge.
  date: 2020-06-16
  image: https://raw.githubusercontent.com/Blackangoo/DDLS_Project/main/results_images/datasets/pFedMe_performance.png
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2006.08848
    - type: source
      text: Code Repository
      link: https://github.com/Blackangoo/DDLS_Project
  tags:
    - personalized federated learning
    - moreau envelopes
    - statistical heterogeneity
    - machine learning
    - distributed systems
  repo: Blackangoo/DDLS_Project

- id: arxiv:1910.13067
  type: paper
  description: A comprehensive study of federated learning over wireless networks, providing convergence analysis and resource allocation optimization for mobile user equipments with heterogeneous data and physical resources.
  date: 2019-10-29
  image: https://via.placeholder.com/400x300/4CAF50/FFFFFF?text=Wireless+Federated+Learning
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/1910.13067
    - type: source
      text: IEEE Xplore
      link: https://doi.org/10.1109/TNET.2020.3035770
  tags:
    - federated learning
    - wireless networks
    - convergence analysis
    - resource allocation
    - mobile computing
    - distributed systems
  journal: IEEE/ACM Transactions on Networking

- id: doi:10.1109/TNNLS.2022.3224252
  type: paper
  description: A novel federated multi-task learning framework using Laplacian regularization that unifies conventional federated learning, personalized federated learning, and federated multi-task learning. Proposes FedU and dFedU algorithms with proven convergence rates.
  date: 2023-01-01
  image: https://via.placeholder.com/400x300/2196F3/FFFFFF?text=Federated+Multi-Task+Learning
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2102.07148
    - type: source
      text: IEEE Xplore
      link: https://doi.org/10.1109/TNNLS.2022.3224252
    - type: source
      text: Code Repository
      link: https://github.com/CharlieDinh/FedU_FMTL
  tags:
    - federated multi-task learning
    - laplacian regularization
    - personalized federated learning
    - convergence analysis
    - distributed systems
    - machine learning
  journal: IEEE Transactions on Neural Networks and Learning Systems
  repo: CharlieDinh/FedU_FMTL

- id: arxiv:2212.12121
  type: paper
  description: A federated principal component analysis (PCA) framework on Grassmann manifold for IoT anomaly detection. The method uses privacy-preserving federated learning to aggregate normal network behavior features across IoT devices, with ADMM-based gradient learning on Grassmann manifolds for fast training and low detection latency.
  date: 2023-01-01
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2212.12121
    - type: source
      text: IEEE INFOCOM
      link: https://doi.org/10.1109/INFOCOM53939.2023.10228884
  tags:
    - federated learning
    - PCA
    - grassmann manifold
    - IoT
    - anomaly detection
    - privacy-preserving
    - ADMM
  journal: IEEE INFOCOM 2023

- id: arxiv:2206.01432
  type: paper
  description: A Wasserstein distributionally robust optimization approach (WAFL) for federated learning that addresses non-i.i.d. data distribution problems. The method reformulates robust federated learning as empirical surrogate risk minimization with convergence guarantees, showing better generalization than FedAvg under distribution shifts.
  date: 2022-06-02
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2206.01432
  tags:
    - federated learning
    - wasserstein distance
    - distributionally robust optimization
    - non-iid data
    - generalization
    - robustness
  journal: arXiv preprint

- id: doi:10.1007/s11036-024-02316-w
  type: paper
  description: A distributionally robust federated learning framework designed for mobile edge networks that addresses data heterogeneity and distribution shifts in edge computing environments. The method enhances robustness and generalization capabilities in resource-constrained mobile edge settings.
  date: 2024-01-01
  buttons:
    - type: source
      text: Springer
      link: https://doi.org/10.1007/s11036-024-02316-w
  tags:
    - federated learning
    - mobile edge computing
    - distributionally robust optimization
    - edge networks
    - robustness
    - heterogeneity
  journal: Mobile Networks and Applications

- id: doi:10.48550/ARXIV.2506.03167
  type: paper
  description: A distributionally robust approach for wireless semantic communication with large AI models that addresses uncertainty in wireless channels and semantic information transmission, enhancing reliability in AI-powered communication systems.
  date: 2024-01-01
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2506.03167
  tags:
    - semantic communication
    - large AI models
    - distributionally robust optimization
    - wireless communication
    - uncertainty
    - robustness
  journal: arXiv preprint

- id: arxiv:2407.07421
  type: paper
  description: A federated learning framework combining Koopman operator theory and reservoir computing for large-scale multivariate time-series anomaly detection. The method leverages dynamic system modeling to detect anomalies in distributed time-series data while preserving privacy.
  date: 2024-07-10
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2407.07421
  tags:
    - federated learning
    - koopman operator
    - reservoir computing
    - time-series analysis
    - anomaly detection
    - multivariate data
    - privacy-preserving
  journal: arXiv preprint

- id: arxiv:2309.15659
  type: paper
  description: A federated deep equilibrium learning approach that harnesses compact global representations to enhance personalization in federated settings. The method addresses the trade-off between personalization and global knowledge sharing through equilibrium point modeling.
  date: 2024-05-22
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2309.15659
  tags:
    - federated learning
    - deep equilibrium learning
    - personalization
    - global representations
    - equilibrium modeling
    - knowledge sharing
  journal: arXiv preprint

- id: arxiv:2405.15230
  type: paper
  description: iREPO introduces an implicit reward pairwise difference based empirical preference optimization framework for aligning large language models with human expectations. The method uses regression on preference pairs to optimize model alignment more effectively.
  date: 2024-05-24
  buttons:
    - type: source
      text: ArXiv
      link: https://arxiv.org/abs/2405.15230
  tags:
    - preference optimization
    - large language models
    - human alignment
    - empirical optimization
    - reward modeling
    - LLM alignment
  journal: arXiv preprint
